In [7]:
import cv2
video = cv2.VideoCapture("policlinica_12s.mp4") #my_cfg.video_file_name "file.ts"
num_frames = int(video.get(cv2.CAP_PROP_FRAME_COUNT))
w = int(video.get(cv2.CAP_PROP_FRAME_WIDTH))
h = int(video.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = int(video.get(cv2.CAP_PROP_FPS))


#https://cams.is74.ru/live/main/cam964.m3u8

In [57]:
import cv2, numpy

image = cv2.imread('images/out1512_2.png',cv2.IMREAD_COLOR)

In [56]:
h = len(image)
w = len(image[0])
image2 = [[[0,0,0] for i in range(w)] for j in range(h)]
hh, ww, lenhw = 0, 0, 0
for i in range(h):
    for j in range(w):
        rr = 0
        for k in range(3):            
            if image[i][j][k] == 255:
                rr+=1
        if rr == 3:
            print(i, j)
            hh+=i
            ww+=j
            lenhw+=1            
            image2[i][j] = [255,255,255]
print(hh / lenhw, ww/lenhw)

552 800
552 801
552 802
552 803
553 799
553 800
553 801
553 802
553 803
554 799
554 800
554 801
554 802
554 803
555 800
555 801
555 802
555 803
553.5 801.2222222222222


In [54]:
cv2.imwrite('images/out1512_2_green22.png',numpy.array(image2))

True

In [62]:
BGR_image = cv2.imread('images/out1512_2.png')
RGB_image = cv2.cvtColor(BGR_image, cv2.COLOR_BGR2RGB)

In [59]:
RGB_image[553][801]

array([111, 222, 175], dtype=uint8)

In [28]:
print(RGB_image[559][801])

[102 255 208]


In [27]:
print(RGB_image[558][801])

[ 83 248 189]


In [21]:
hsv_pixel = cv2.cvtColor([[BGR_image[559][801]]], cv2.COLOR_BGR2HSV)
print(hsv_pixel)

TypeError: Expected Ptr<cv::UMat> for argument 'src'

In [22]:
import colorsys

In [61]:
r, g, b = BGR_image[553][801][::-1] 
print(RGB_green_pixel)
hsv_pixel = colorsys.rgb_to_hsv(r,g,b)
h_ = hsv_pixel[0] * 360
print(hsv_pixel[0] * 360)


[102 255 208]
156.41379296779633


In [48]:
hue = 184
hue_green = True if hue > 80 and hue < 170 else False

In [49]:
hue_green

False